! DO NOT EDIT THIS FILE!!!
!
! This file is automatically generated by write_probin.py at
! compile-time.
!
! To add a runtime parameter, do so by editting the appropriate _parameters
! file.

! This module stores the runtime parameters.  The probin_init() routine is
! used to initialize the runtime parameters

module extern_probin_module

  use bl_types
  use bl_space

  implicit none

  private

  logical, save, public :: use_eos_coulomb = .true.
  logical, save, public :: eos_input_is_constant = .false.
  integer, save, public :: eos_acc_cutoff = 128
  logical, save, public :: eos_do_acc = .true.
  real (kind=dp_t), save, public :: const_conductivity = 1.0d0
  real (kind=dp_t), save, public :: const_viscosity = 1.0d-4

end module extern_probin_module

subroutine runtime_init(name,namlen)

  use extern_probin_module

  implicit none

  integer :: namlen
  integer :: name(namlen)

  integer :: un, i, status

  integer, parameter :: maxlen = 256
  character (len=maxlen) :: probin


  namelist /extern/ use_eos_coulomb
  namelist /extern/ eos_input_is_constant
  namelist /extern/ eos_acc_cutoff
  namelist /extern/ eos_do_acc
  namelist /extern/ const_conductivity
  namelist /extern/ const_viscosity

  use_eos_coulomb = .true.
  eos_input_is_constant = .false.
  eos_acc_cutoff = 128
  eos_do_acc = .true.
  const_conductivity = 1.0d0
  const_viscosity = 1.0d-4


  ! create the filename
  if (namlen > maxlen) then
     print *, 'probin file name too long'
     stop
  endif

  do i = 1, namlen
     probin(i:i) = char(name(i))
  end do


  ! read in the namelist
  un = 9
  open (unit=un, file=probin(1:namlen), form='formatted', status='old')
  read (unit=un, nml=extern, iostat=status)

  if (status < 0) then
     ! the namelist does not exist, so we just go with the defaults
     continue

  else if (status > 0) then
     ! some problem in the namelist
     print *, 'ERROR: problem in the extern namelist'
     stop
  endif

  close (unit=un)
    
end subroutine runtime_init

